### PR TITLE
fix release src cannot compile bug

### PR DESCRIPTION
**Pull request by EvanLjp**
fix release src cannot compile bug

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Seems I can't still compile from the src.tgz made from this branch?

**Comment by EvanLjp** [comment]
image
maybe could compile on my mac.

**Comment by kezhenxu94** [comment]
@EvanLjp see my update 👆

**Comment by wu-sheng** [comment]
@kezhenxu94 @EvanLjp I think this is why we use a `shell` rather than a simple make file to build src release.

@kezhenxu94 didn't do `git submodule init/update`, but run `make release-src`, then still src is not complete.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/master/tools/releasing/create_source_release.sh Like I asked, take a look at the main repo, the whole process matters.

**Review by kezhenxu94 — APPROVED** [review]
Turns out to be my local Go env problem :(

**Comment by EvanLjp** [comment]
> @kezhenxu94 @EvanLjp I think this is why we use a `shell` rather than a simple make file to build src release.
> 
> @kezhenxu94 didn't do `git submodule init/update`, but run `make release-src`, then still src is not complete.

protocol files have been already added to src release.

**Comment by wu-sheng** [comment]
> protocol files have been already added to src release.

Try this, use an empty folder, do git clone, then `make`. Your tar ball is broken.

**Comment by wu-sheng** [comment]
You are feeling good, because you use your dev env.

**Pull request merged**
